<template>
  <header class="main-header has-text-centered">
    <h1 class="is-size-5 has-text-weight-medium">Vue Quiz App</h1>
  </header>
  <main class="main-ctr">
    <template v-if="completed">
      <callout
        :status="status"
        :correct="totalCorrectAnswers"
        :numOfQuestions="questions.length"
      ></callout>
      <div class="has-text-centered emoji" v-if="completed">
        <span v-if="status === 'success'">🎊</span>
        <span v-else>😔</span>
      </div>
      <div v-if="completed">
        <button
          type="button"
          class="button is-danger has-text-weight-medium is-fullwidth"
          @click="handleReset()"
        >
          Restart Quiz
        </button>
      </div>
    </template>

    <questions
      :questions="questions"
      :currentQuestion="currentQuestion"
      :totalCorrectAnswers="totalCorrectAnswers"
      :completed="completed"
      @next-question="handleNext()"
      @correct-answer="totalCorrectAnswers = $event"
      v-else
    ></questions>
  </main>
  <footer class="has-text-centered">
    <p>
      &copy; {{ new Date().getFullYear() }}. Questions generated by Chat-GPT.
    </p>
  </footer>
</template>

<script>
import Callout from "@/components/Callout.vue";
import Questions from "@/components/Questions.vue";

export default {
  components: {
    Callout,
    Questions,
  },
  methods: {
    handleNext() {
      this.currentQuestion++;
    },
    handleReset() {
      this.currentQuestion = 0;
      this.totalCorrectAnswers = 0;
    },
  },
  data() {
    return {
      currentQuestion: 0,
      passingScore: 5,
      totalCorrectAnswers: 0,
      questions: [
        {
          question: "What is the capital of France?",
          answers: ["Berlin", "Rome", "Paris", "Madrid"],
          correctAnswer: 2,
        },
        {
          question: "Which planet is known as the Red Planet?",
          answers: ["Mars", "Venus", "Jupiter", "Saturn"],
          correctAnswer: 0,
        },
        {
          question: "What is the largest mammal?",
          answers: ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"],
          correctAnswer: 1,
        },
        {
          question: "Who painted the Mona Lisa?",
          answers: [
            "Vincent van Gogh",
            "Pablo Picasso",
            "Leonardo da Vinci",
            "Claude Monet",
          ],
          correctAnswer: 2,
        },
        {
          question: "What gas do plants use for photosynthesis?",
          answers: ["Oxygen", "Carbon Dioxide", "Hydrogen", "Nitrogen"],
          correctAnswer: 1,
        },
        {
          question:
            "Which famous scientist developed the theory of general relativity?",
          answers: [
            "Isaac Newton",
            "Albert Einstein",
            "Galileo Galilei",
            "Stephen Hawking",
          ],
          correctAnswer: 1,
        },
        {
          question: "What is the largest organ in the human body?",
          answers: ["Liver", "Brain", "Heart", "Skin"],
          correctAnswer: 3,
        },
        {
          question: "Which gas do plants release during photosynthesis?",
          answers: ["Oxygen", "Carbon Dioxide", "Methane", "Nitrogen"],
          correctAnswer: 0,
        },
        {
          question: "In which year did the Titanic sink?",
          answers: ["1902", "1912", "1922", "1932"],
          correctAnswer: 1,
        },
        {
          question: "Who wrote the play 'Romeo and Juliet'?",
          answers: [
            "William Shakespeare",
            "Charles Dickens",
            "Mark Twain",
            "Jane Austen",
          ],
          correctAnswer: 0,
        },
      ],
    };
  },
  computed: {
    completed() {
      return this.currentQuestion >= this.questions.length;
    },
    status() {
      return this.totalCorrectAnswers >= this.passingScore
        ? "success"
        : "error";
    },
  },
};
</script>

<style lang="scss"></style>
